spring.application.name=metabase-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/metabase
spring.datasource.username=metabase
spring.datasource.password=metabase
spring.flyway.enabled=true
spring.graphql.graphiql.enabled=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
metabase.graphql.max-query-depth=${GRAPHQL_MAX_QUERY_DEPTH:20}
metabase.graphql.max-query-complexity=${GRAPHQL_MAX_QUERY_COMPLEXITY:500}

